name: Tests

on:
  pull_request:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*'

jobs:
  test:
    name: 'Rails ${{ matrix.rails }} × Ruby ${{ matrix.ruby }}'
    # Skip running tests for local pull requests (use push event instead), run only for foreign ones
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.owner.login != github.event.pull_request.base.repo.owner.login
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ruby:  "3.2"
          - ruby:  "3.1"
          - ruby:  "3.2"
          - ruby:  "3.1"
          - ruby:  "3.0"
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run specs
      run: bundle exec rake spec
